/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.carshop.application;

import java.util.ArrayList;

import ca.mcgill.ecse.carshop.model.CarShop;
import ca.mcgill.ecse.carshop.model.Owner;
import ca.mcgill.ecse.carshop.model.Technician;
import ca.mcgill.ecse.carshop.model.User;
import ca.mcgill.ecse.carshop.persistence.CarShopPersistence;
import ca.mcgill.ecse.carshop.view.LogInView;
import ca.mcgill.ecse.carshop.view.UpdateAppointmentView;
import ca.mcgill.ecse.carshop.view.test;

import java.awt.EventQueue;
import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;

import ca.mcgill.ecse.carshop.controller.BusinessHourTO;
import ca.mcgill.ecse.carshop.controller.CarShopController;
import ca.mcgill.ecse.carshop.controller.InvalidInputException;
import ca.mcgill.ecse.carshop.model.Appointment;
import ca.mcgill.ecse.carshop.model.Business;
import ca.mcgill.ecse.carshop.model.BusinessHour;
import ca.mcgill.ecse.carshop.model.Technician.TechnicianType;


public class CarShopApplication {

	private static CarShop carshop;
	private static Date date;
	private static Time time;
	private static LocalDate currentDate;
	private static LocalTime currentTime;
	public static LogInView mainframe;
	

	// keeps track of the currently logged in users
	private static ArrayList<User> loggedIn = new ArrayList<User>();

	public static String getGreeting() {
		return "Welcome to Group7 CarShop Application";
	}
	
	public static void main(String[] args) {
		carshop = getCarShop();
		

		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					LogInView window = new LogInView();
					window.getFrame().setVisible(true);
					mainframe = window;
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
		
		
//********************Uncomment This to Quickly Test view for different users **************************//		
//		String greeting = getGreeting();
//		System.out.println(getGreeting());
//		
//		
//		if (carshop.getBusiness() == null)
//			new Business("dummyName", "dummyAddress", "dummyPhoneNumber", "dymmyEmail", carshop);
//	
//		carshop.getBusiness().addBusinessHour(new BusinessHour(CarShopController.parseStringToDayOfWeek("Monday"), Time.valueOf("09:00:00"), Time.valueOf("18:00:00"), carshop));
//		carshop.getBusiness().addBusinessHour(new BusinessHour(CarShopController.parseStringToDayOfWeek("Tuesday"), Time.valueOf("10:00:00"), Time.valueOf("18:00:00"), carshop));
//		carshop.getBusiness().addBusinessHour(new BusinessHour(CarShopController.parseStringToDayOfWeek("Friday"), Time.valueOf("11:00:00"), Time.valueOf("18:00:00"), carshop));
//
//		
		
//**********************************************************************************************************//		
		
		
		

	// Uncomment to try persistence
////		//debugging - making sure persistence is working correctly
////        CarShop c = CarShopPersistence.load();
////        c.addCustomer("test1", "test2");
////        CarShopPersistence.save(c);
////        System.out.println(c.getCustomer(0));
	}

	public static void add(User user) {
		loggedIn.add(user);
	}

	public static boolean isLoggedin(User user) {
		return loggedIn.contains(user);
	}

	public static boolean isLoggedin(String username) {
		boolean	exist = false;
		for(User u: loggedIn) {
			if(u.getUsername() == username) {
				exist = true;
			}
		}
		return exist;
	}
	
  	public static User getRecentlyLogedinUser() {
  		if(loggedIn.size()==0) return null;
  		return loggedIn.get(loggedIn.size() - 1);
  	}
	
	public static void logoutRecentlyLogedinUser() {
		if (loggedIn.size() != 0)
			loggedIn.remove(loggedIn.size() - 1);
	}
	
	// returns the CarShop object -- create new if it doesnt exist
    /**
     * Toggle to 2, if cucumber testing is being done, else toggle to 1 for
     * persistence functionality to work
     * 
     */

    public static CarShop getCarShop() {
        if (carshop == null) {
            // carshop = (CarShop) CarShopPersistence.load(); //--1
            carshop = new CarShop(); // --2
        }
        return carshop;
    }
	
	public static void setDate(Date systemDate) {
		date = systemDate;
	}
	
	public static void setTime(Time systemTime) {
		time = systemTime;
	}
	
	public static Date getDate() {
		return date;
	}
	
	public static Time getTime() {
		return time;
	}
	
	public static LocalDate getLocalDate(){
		return currentDate;
	}
	
	public static LocalTime getLocalTime(){
		return currentTime;
	}
	
	public static LocalDate getDateNow(){
		currentDate=LocalDate.now();
		return currentDate;
	}
	
	public static LocalTime getTimeNow() {
		currentTime=LocalTime.now();
		return currentTime;
	}
	
	public static void setLocalDate(String string) {
		java.sql.Date date=java.sql.Date.valueOf(string);
		currentDate=date.toLocalDate();
		
	}
	
	public static void setLocalTime(String string) {
		java.sql.Time time=java.sql.Time.valueOf(string);
		currentTime=time.toLocalTime();
	}
	public static LogInView getLogInView() {
		return mainframe;
	}
}
